### PR TITLE
Enemies

### PR DESCRIPTION
**Pull request by phllpbll189**
I added enemies.cpp and enemies.h.

Its a class with basic functionality for right now and it records stats like

1. speed

2. armor

3. health

with a default constructor and one overloaded constructor

The destructor i was curious about. We could make the item drop in the destructor if we would want to.

### CODE REVIEW

**Review by PointlessVenture — COMMENTED** [review]
You should remove the .vs and Debug files before submitting pulls to help minimize update size. Actual file changes are good though, we can certainly push those in.

**Comment by phllpbll189** [comment]
okay sounds good, can you still see whats in the enemies.cpp and .h? just so people can start working by seeing whats in it and how it would work.

**Comment by phllpbll189** [comment]
@PointlessVenture I managed to delete those two files. If it all looks good to you i think its ready.

**Comment by PointlessVenture** [comment]
i'm sorry i didn't make this clear, but you should remove _everything_ except changes you made to enemies.cpp, enemies.h, and main.cpp. those should be the only 3 files in the pull request. I have reviewed the changes in those files and they are good to go.

**Comment by phllpbll189** [comment]
okay sounds good

**Comment by phllpbll189** [comment]
@PointlessVenture like that? i deleted absolutely everything other than the main and enemies

**Pull request merged**
