### PR TITLE
Set up beginning of the game. More to add later.

### PR DESCRIPTION
**Pull request by JHump20**
I created a basic beginning so we can start to branch off in our own directions. I plan to add more in the next few days.

### CODE REVIEW

**Comment by PointlessVenture** [comment]
@JHump20 This should probably use the room system. Otherwise it's gonna be really hard to integrate it.

**Comment by JHump20** [comment]
@PointlessVenture How should I do that? I thought that was for our own specific branches of rooms.

**Comment by PointlessVenture** [comment]
Declare a room class, with any name you want.
Create a vector of strings to be the description of that room. (each line should be 1 string)
Put the vector of strings in the room using the addRoomDescription function
Run executeRoom() on your room class.

**Comment by PointlessVenture** [comment]
The reason that that is going to be important is, if we ever want to make rooms that come off of this room, or be able to come back to room one, we'll need links, which given the way i've set them up, need a pointer to a room.

**Comment by JHump20** [comment]
Alright I will figure it out thanks.

**Pull request closed without merging**
